# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ziluepan/ziluepan.github.io"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Docs"
name = "docs"
url = "https://stack.jimmycai.com/config/"

[social.params]
icon = "anchor"

[[social]]
identifier = "Stars"
name = "stars"
url = "https://www.ificould.xyz"

[social.params]
icon = "stars"
